### ISSUE TITLE
db inserts fail immediately after seeding

### ISSUE THREAD

**Issue by andycmaj** [asynchronous-dev/botany#27]
looks like possibly sequences are out of sync immediatley after seeding:

1. reset db
2. try to create a github connection

```
auth:github error upserting user { GraphQLError: Uniqueness violation. duplicate key value violates unique constraint "user_pkey"
    at Object.locatedError (/Workspace/github/asynchronous-dev/botany/node_modules/graphql/error/locatedError.js:22:10)
    at Object.checkResultAndHandleErrors (/Workspace/github/asynchronous-dev/botany/node_modules/graphql-tools/dist/stitching/errors.js:99:23)
    at /Workspace/github/asynchronous-dev/botany/node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js:156:52
    at step (/Workspace/github/asynchronous-dev/botany/node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js:31:23)
    at Object.next (/Workspace/github/asynchronous-dev/botany/node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js:12:53)
    at fulfilled (/Workspace/github/asynchronous-dev/botany/node_modules/graphql-tools/dist/stitching/makeRemoteExecutableSchema.js:3:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Uniqueness violation. duplicate key value violates unique constraint "user_pkey"',
  locations: [],
  path: [ 'insert_user' ],
  extensions:
   { path: '$.selectionSet.insert_user.args.objects[0]',
     code: 'constraint-violation' } }**
```

the pk is the id column in the user or` userDtaaSource` table in psql
and the seeding process created rows in those tables with literal id=1
which make the auto-sequence generators get out of sync (because we didn't let them generate the next id integer)

**Comment by andycmaj** [comment]
to workaround for now, you just have to try and fail twice (so the failures reset the sequeneces for the `user` and `userDataSoruce` tables.) then it should work... so keep clearing cookies and retrying
